---
- name: Updates in the node servers
  hosts: testservers
  remote_user: root
  tasks:
  - name: Update apt
    apt: update-cache=yes
  - name: Install JDK
    apt:
      name: openjdk-17-jdk
      state: latest
  - name: Install basic system packages
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - vim
      - htop
      - curl
      - wget
  - name: Install Python and Node.js
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - python3
      - nodejs

- name: Reboot
  hosts: el_patching_all_reboot
  remote_user: root
  vars:
    el_patching_method: "all"
    el_patching_auto_reboot: true
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
