---
- name: Install Java dev environment in Project1 servers
  hosts: project1
  remote_user: root
  tasks:
  - name: Update apt package cache
    apt: update-cache=yes
  - name: Install JDK
    apt:
      name: openjdk-17-jdk
      state: latest 
- name: Install Python dev environment in Project2 servers
  hosts: project2
  remote_user: root
  tasks:  
  - name: Install Python and Node.js
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - python3
      - nodejs
- name:  Copy mandatory patch files and execute scripts on all dev servers
  hosts: allservers
  remote_user: root
  tasks:  
  - name: Copy files to target nodes
    ansible.builtin.copy: 
      src: /root/ansible/demo.txt
      dest: /root/demo.txt
  - name: Execute a script
    script: /root/ansible/script.sh

- name: Rebooting all systems after patching
  hosts: allservers
  become: true
  remote_user: root
  vars:
    # defaults
    reboot_timeout: 600
    auto_reboot: true
  tasks:
  - name: Inform user that a reboot is required
    ansible.builtin.debug:
      msg: "Reboot is required to apply patches."
  - name: Reboot host
    ansible.builtin.reboot:
      reboot_timeout: "{{ reboot_timeout }}"
    when: auto_reboot | bool
